name: Docker build CI

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      -
        name: Checkout 
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - 
        name: Login to private registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.NEXUS_URL }}
          username: ${{ secrets.NEXUS_USERNAME }}
          password: ${{ secrets.NEXUS_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: '${{ secrets.NEXUS_URL }}/j6/authy:main-dev-{{ github.run_number }}'
          cache-from: 'type=registry,ref=${{ secrets.NEXUS_URL }}/j6/authy:buildcache'
          cache-to: 'type=registry,ref=${{ secrets.NEXUS_URL }}/j6/authy:buildcache,mode=max'