name: Docker build CI

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      -
        name: Checkout 
        uses: actions/checkout@v2

      - name: Set up Node and install dependencies
        uses: actions/setup-node@v3
        with:
          node-version: '16.8.0'
      - run: npm i next@latest react@latest react-dom@latest
      - run: npm install --omit=dev
      - run: npm run build

      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - 
        name: Login to private registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.NEXUS_URL }}
          username: ${{ secrets.NEXUS_USER }}
          password: ${{ secrets.NEXUS_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: '${{ secrets.NEXUS_URL }}/j6/authy:main-dev-${{ github.run_number }}'
